import type { Metadata } from "next";
import { Lexend, Kufam } from "next/font/google"; // ✅ import Kufam
import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",   // ✅ added variable for Lexend
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

const kufam = Kufam({
  variable: "--font-kufam",   // ✅ added variable for Kufam
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${kufam.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
